"""Writes docs/pipeline.md from the Dagster definitions: group lineage, jobs, triggers.

    python -m waferlens.orchestration.docs      (or: make pipeline-docs)

Generated from the real asset graph, so it can't drift from the code.
"""

from collections import Counter
from pathlib import Path

from dagster import Definitions, ScheduleDefinition

ROOT = Path(__file__).resolve().parents[3]
OUTPUT = ROOT / "docs" / "pipeline.md"
GROUP_ORDER = ["ingest", "warehouse", "dbt_staging", "dbt_intermediate", "dbt_marts"]


def group_lineage(defs: Definitions) -> tuple[Counter[str], Counter[tuple[str, str]]]:
    graph = defs.resolve_asset_graph()
    sizes: Counter[str] = Counter()
    edges: Counter[tuple[str, str]] = Counter()
    for key in graph.get_all_asset_keys():
        node = graph.get(key)
        group = node.group_name or "default"
        sizes[group] += 1
        for parent in node.parent_keys:
            parent_group = graph.get(parent).group_name or "default"
            if parent_group != group:
                edges[(parent_group, group)] += 1
    return sizes, edges


def render(defs: Definitions) -> str:
    graph = defs.resolve_asset_graph()
    sizes, edges = group_lineage(defs)
    checks = list(graph.asset_check_keys)
    dbt_checks = [k for k in checks if (graph.get(k.asset_key).group_name or "").startswith("dbt_")]
    own_checks = sorted(
        f"`{k.name}` on `{k.asset_key.to_user_string()}`"
        + (" (blocking)" if graph.get_check_spec(k).blocking else "")
        for k in checks
        if k not in dbt_checks
    )

    lines = ["```mermaid", "flowchart LR"]
    order = [g for g in GROUP_ORDER if g in sizes] + sorted(set(sizes) - set(GROUP_ORDER))
    for group in order:
        noun = "asset" if sizes[group] == 1 else "assets"
        lines.append(f'    {group}["{group}<br/>{sizes[group]} {noun}"]')
    for (a, b), n in sorted(
        edges.items(), key=lambda e: (order.index(e[0][0]), order.index(e[0][1]))
    ):
        lines.append(f"    {a} -->|{n}| {b}")
    lines.append("```")

    jobs = sorted(
        (j for j in defs.resolve_all_job_defs() if not j.name.startswith("__")),
        key=lambda j: j.name,
    )
    job_rows = "\n".join(
        f"| `{j.name}` | {len(j.asset_layer.selected_asset_keys)} | {j.description or ''} |"
        for j in jobs
    )
    sensors = "\n".join(
        f"| sensor | `{s.name}` | `{s.job_name}` | every {s.minimum_interval_seconds} s |"
        for s in defs.sensors or []
    )
    schedules = "\n".join(
        f"| schedule | `{s.name}` | `{s.job_name}` | `{s.cron_schedule}` ({s.execution_timezone}) |"
        for s in defs.schedules or []
        if isinstance(s, ScheduleDefinition)
    )
    return f"""# Pipeline (Dagster)

Generated by `make pipeline-docs` from `waferlens.orchestration.definitions`; don't edit by hand.

{sum(sizes.values())} assets in {len(sizes)} groups and {len(checks)} asset checks:
{", ".join(own_checks)}, plus {len(dbt_checks)} dbt tests, which dagster-dbt runs as blocking
checks on the model they test. Edge labels count the asset-to-asset links between groups.

## Lineage by group

{chr(10).join(lines)}

## Jobs

| Job | Assets | What it does |
|---|---|---|
{job_rows}

## Triggers (start stopped; enable in the UI)

| Kind | Name | Runs | When |
|---|---|---|---|
{sensors}
{schedules}
"""


def main() -> None:
    from waferlens.orchestration.definitions import defs

    OUTPUT.write_text(render(defs))
    print(f"wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
