"""Renders docs/fabeye_eval.md: FabEye on simulated wafer maps vs its own numbers on real lots."""

from __future__ import annotations

import numpy as np

from waferlens.patterns.evaluate import Evaluation

# FabEye's lot-grouped test result (github.com/anson10/FabEye README); not served by its API.
FABEYE_REAL_MACRO_F1 = 0.858


def _pct(x: float) -> str:
    return "–" if x is None or np.isnan(x) else f"{100 * x:.1f}%"


def headline_table(ev: Evaluation) -> str:
    ref = ev.reference
    accept = ref["accept"]
    rows = ["| | Simulated fab (here) | FabEye on unseen real lots |", "|---|---|---|",
            f"| Wafers | {len(ev.frame):,} sorted | WM-811K lots never used in training |",
            f"| Macro-F1 (patterns present) | {ev.macro_f1:.3f} | {FABEYE_REAL_MACRO_F1:.3f} |",
            f"| Accuracy | {_pct(ev.accuracy)} (always 'none': {_pct(ev.majority_accuracy)}) | |",
            f"| 90% prediction set covers the truth | {_pct(ev.coverage)} | "
            f"{_pct(ref['coverage'])} |",
            f"| Auto-accepted | {_pct(ev.accept_rate)} | "
            f"{_pct(accept['unseen_lot_accept_rate'])} |",
            f"| Error among auto-accepted (target ≤ {_pct(accept['target_error'])}) | "
            f"{_pct(ev.accepted_error)} | "
            f"{_pct(accept['unseen_lot_error_among_accepted'])} |"]  # fmt: skip
    return "\n".join(rows)


def per_class_table(ev: Evaluation) -> str:
    rows = ["| Class | True wafers | Predicted | Recall | Precision | Set coverage |",
            "|---|---|---|---|---|---|"]  # fmt: skip
    for r in ev.per_class.to_dict("records"):
        rows.append(f"| {r['class']} | {r['true']:,} | {r['predicted']:,} | {_pct(r['recall'])} "
                    f"| {_pct(r['precision'])} | {_pct(r['coverage'])} |")  # fmt: skip
    return "\n".join(rows)


def confusion_table(ev: Evaluation) -> str:
    cm = ev.confusion
    cols = list(cm.columns)
    rows = ["| True ↓ / predicted → | " + " | ".join(cols) + " |",
            "|---" * (len(cols) + 1) + "|"]  # fmt: skip
    for truth, row in cm.iterrows():
        rows.append(f"| **{truth}** | " + " | ".join(f"{int(v):,}" for v in row) + " |")
    return "\n".join(rows)


def magnitude_table(ev: Evaluation) -> str:
    rows = ["| Injected strength | Pattern wafers | Correct pattern | Any pattern (not 'none') |",
            "|---|---|---|---|"]  # fmt: skip
    for r in ev.by_magnitude.to_dict("records"):
        rows.append(f"| {r['magnitude']} | {int(r['wafers']):,} | {_pct(r['recall'])} | "
                    f"{_pct(r['detected'])} |")  # fmt: skip
    return "\n".join(rows)


def false_alarm_line(ev: Evaluation) -> str:
    clean = ev.frame[ev.frame["truth"] == "none"]
    flagged = clean[clean["predicted"] != "none"]
    top = flagged["predicted"].value_counts().head(3)
    listed = ", ".join(f"{k} {v:,}" for k, v in top.items()) or "none"
    empty = int((ev.frame["prediction_set"].map(len) == 0).sum())
    return (
        f"Of {len(clean):,} wafers without an injected pattern, FabEye called "
        f"{len(flagged):,} ({_pct(len(flagged) / max(len(clean), 1))}) a pattern: {listed}. "
        f"{empty:,} wafers got an empty prediction set: no class looked plausible, a sign the "
        "map is unlike FabEye's calibration lots."
    )


def weak_classes(ev: Evaluation, floor: float = 0.9) -> str:
    """Classes whose recall or set coverage falls below ``floor``, with their main confusion."""
    lines = []
    present = ev.per_class[ev.per_class["true"] > 0]
    for r in present.to_dict("records"):
        if r["recall"] >= floor and r["coverage"] >= floor:
            continue
        row = ev.confusion.loc[r["class"]].drop(r["class"], errors="ignore")
        worst = f"; mostly called {row.idxmax()} ({int(row.max()):,})" if row.max() > 0 else ""
        lines.append(f"- **{r['class']}**: recall {_pct(r['recall'])}, set coverage "
                     f"{_pct(r['coverage'])} against FabEye's ~90%{worst}.")  # fmt: skip
    return "\n".join(lines) or "- None: every class present has recall and coverage ≥ 90%."


def render(ev: Evaluation, model: str) -> str:
    pattern = ev.frame["truth"] != "none"
    return f"""# FabEye on simulated wafer maps

Generated by `make fabeye-report`; don't edit by hand. FabEye
([github.com/anson10/FabEye](https://github.com/anson10/FabEye), `{model}`) classifies every
sorted wafer map through its `/predict/batch` API (`waferlens.patterns`); the simulator logs
which wafers show an injected pattern (`wafer_pattern_truth`), so every prediction can be
scored. FabEye was trained and calibrated on real WM-811K lots and never on these maps: this
is a domain-shift test, not a retraining.

## Headline

{headline_table(ev)}

{int(pattern.sum()):,} wafers carry an injected pattern; FabEye called
{_pct(ev.pattern_detected)} of them *some* pattern. {false_alarm_line(ev)}

## Per class

{per_class_table(ev)}

Set coverage is the share of a class's wafers whose 90% conformal prediction set contains
the true class; FabEye guarantees ~90% per class on lots like its calibration lots.

## Confusion matrix

{confusion_table(ev)}

## By injected strength

{magnitude_table(ev)}

The simulator draws each spatial excursion's strength; a weak pattern adds only a few failing
dies, which a human labeller would also call "none".

## Where the guarantees break

{weak_classes(ev)}

FabEye's prediction sets and accept rule assume new lots resemble its calibration lots (its
`/calibration` endpoint says so). The classes above are where the simulated maps stop
resembling them.

## What this does and doesn't show

- **It is an easier test than real data.** The simulator's patterns are clean parametric
  shapes (a Gaussian centre, a ring at r = 0.8–0.92) on a uniform background; real WM-811K
  patterns are messier. Scores above FabEye's real-lot numbers say more about the simulator
  than about FabEye.
- **The shift is real where shapes overlap:** a strong uniform "random" defect field fails
  so many dies that it looks like WM-811K's Near-full, and small maps (24–40 dies across,
  resized to 64 × 64) blur thin scratches.
- **Calibration over-covers on clean classes:** coverage above 90% means the sets are wider
  than needed here, which costs nothing but shows the calibration doesn't transfer exactly
  in either direction.
"""
