apiVersion: 1

datasources:
  - name: WaferLens Postgres
    uid: waferlens-postgres
    type: postgres
    access: proxy
    url: db:5432
    database: waferlens
    user: waferlens
    isDefault: true
    editable: true
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: waferlens
