apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: waferlens-timescaledb
    type: grafana-postgresql-datasource
    url: db:5432
    user: $POSTGRES_USER
    isDefault: true
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      database: $POSTGRES_DB
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
