"""Schema tests: migrations, TimescaleDB setup, constraints, genealogy queries, yield view."""

from __future__ import annotations

from collections.abc import Callable
from datetime import timedelta

import pytest
from alembic import command
from alembic.config import Config
from sqlalchemy import Engine, inspect, select, text
from sqlalchemy.exc import DBAPIError
from sqlalchemy.orm import Session

from tests.integration.conftest import T0, MiniFab, at
from waferlens.db import models as m

pytestmark = pytest.mark.integration


# --------------------------------------------------------------------------- migrations


def test_migration_creates_every_model_table(engine: Engine) -> None:
    tables = set(inspect(engine).get_table_names())
    assert set(m.Base.metadata.tables) | set(m.ExternalBase.metadata.tables) <= tables


def test_models_and_migrations_are_in_sync(alembic_cfg: Config, engine: Engine) -> None:
    # Raises AutogenerateDiffsDetected if a model changed without a migration.
    command.check(alembic_cfg)


def test_downgrade_to_base_and_back(alembic_cfg: Config, engine: Engine) -> None:
    command.downgrade(alembic_cfg, "base")
    assert "wafers" not in inspect(engine).get_table_names()
    command.upgrade(alembic_cfg, "head")
    assert "wafers" in inspect(engine).get_table_names()


def test_measurement_tables_are_weekly_hypertables(engine: Engine) -> None:
    with engine.connect() as conn:
        rows = conn.execute(
            text(
                "SELECT hypertable_name, column_name, time_interval "
                "FROM timescaledb_information.dimensions "
                # the sensor_daily continuous aggregate keeps its own internal hypertable
                "WHERE hypertable_schema = 'public' ORDER BY hypertable_name"
            )
        ).all()
    assert [(r.hypertable_name, r.column_name, r.time_interval) for r in rows] == [
        ("metrology_measurements", "time", timedelta(days=7)),
        ("tool_sensor_readings", "time", timedelta(days=7)),
    ]


# --------------------------------------------------------------------------- ORM + genealogy


def test_relationships_resolve(db: Session, fab: MiniFab) -> None:
    wafer = db.get(m.Wafer, 2)
    assert wafer is not None
    assert wafer.lot.product.node.name == "28nm"
    assert [c.chamber_code for c in fab.chamber_a.tool.chambers] == ["A", "B"]
    assert [s.step_name for s in fab.route.steps] == ["m1_etch", "m1_cmp"]


def test_split_lot_keeps_parent_link(db: Session, fab: MiniFab) -> None:
    child = m.Lot(
        lot_id=2, lot_code="L26001.2", parent_lot_id=fab.lot.lot_id, product_id=1, route_id=1,
        start_time=at(60), status="active",
    )  # fmt: skip
    db.add(child)
    db.flush()
    db.add(m.LotEvent(lot_id=1, event_type="split", event_time=at(60), related_lot_id=2))
    fab.wafers[2].lot_id = 2
    db.flush()
    db.refresh(child)
    assert child.parent is fab.lot
    assert [w.wafer_id for w in child.wafers] == [3]


def test_commonality_query_finds_wafers_by_chamber_and_window(db: Session, fab: MiniFab) -> None:
    # Wafers 1 and 3 run in chamber A, wafer 2 in chamber B.
    for wafer, chamber, start in [(1, 1, 0), (2, 2, 0), (3, 1, 200)]:
        db.add(
            m.WaferStepHistory(
                wafer_id=wafer, route_step_id=1, lot_id=1, chamber_id=chamber, recipe_id=1,
                track_in=at(start), track_out=at(start + 20),
            )
        )  # fmt: skip
    db.flush()
    hit = db.scalars(
        select(m.WaferStepHistory.wafer_id)
        .where(m.WaferStepHistory.chamber_id == 1)
        .where(m.WaferStepHistory.track_in.between(T0, at(100)))
    ).all()
    assert hit == [1]


def test_rework_is_a_second_pass_not_a_duplicate(db: Session, fab: MiniFab) -> None:
    for pass_no in (1, 2):
        db.add(
            m.WaferStepHistory(
                wafer_id=1, route_step_id=1, pass_no=pass_no, lot_id=1, chamber_id=1,
                recipe_id=1, track_in=at(pass_no * 60), track_out=at(pass_no * 60 + 20),
            )
        )  # fmt: skip
    db.flush()
    assert len(db.get_one(m.Wafer, 1).history) == 2


# --------------------------------------------------------------------------- results


def test_hypertable_rows_land_in_weekly_chunks(db: Session, fab: MiniFab) -> None:
    for week in range(3):
        db.add(
            m.ToolSensorReading(
                time=T0 + timedelta(weeks=week), wafer_id=1, route_step_id=1, parameter_id=1,
                chamber_id=1, value=500.0 + week,
            )
        )  # fmt: skip
    db.flush()
    chunks = db.execute(text("SELECT count(*) FROM show_chunks('tool_sensor_readings')"))
    assert chunks.scalar_one() == 3


def test_wafer_map_round_trips_as_2d_array(db: Session, fab: MiniFab) -> None:
    grid = [[0, 1, 1, 0], [1, 2, 1, 1], [1, 1, 3, 1], [0, 1, 1, 0]]
    db.add(m.WaferMap(wafer_id=1, tested_at=at(500), bin_map=grid))
    db.flush()
    db.expire_all()
    assert db.get_one(m.WaferMap, 1).bin_map == grid


def test_wafer_yield_uses_pass_bins(db: Session, fab: MiniFab) -> None:
    db.add_all(
        [
            m.WaferBinSummary(wafer_id=1, bin_code=1, die_count=72),
            m.WaferBinSummary(wafer_id=1, bin_code=2, die_count=5),
            m.WaferBinSummary(wafer_id=1, bin_code=3, die_count=3),
            m.WaferBinSummary(wafer_id=2, bin_code=2, die_count=80),
        ]
    )
    db.flush()
    db.execute(text("REFRESH MATERIALIZED VIEW wafer_yield"))
    rows = db.execute(
        text("SELECT wafer_id, tested_dies, good_dies, yield_pct FROM wafer_yield ORDER BY 1")
    ).all()
    assert [tuple(r) for r in rows] == [(1, 80, 72, 90), (2, 80, 0, 0)]


# --------------------------------------------------------------------------- constraints

Violation = Callable[[MiniFab], object]

VIOLATIONS: dict[str, Violation] = {
    "slot_out_of_range": lambda f: m.Wafer(
        wafer_id=9, wafer_code="X-26", lot_id=1, slot=26, status="active"
    ),
    "unknown_wafer_status": lambda f: m.Wafer(
        wafer_id=9, wafer_code="X-09", lot_id=1, slot=9, status="lost"
    ),
    "wafer_in_missing_lot": lambda f: m.Wafer(
        wafer_id=9, wafer_code="X-09", lot_id=999, slot=9, status="active"
    ),
    "duplicate_chamber_code": lambda f: m.Chamber(chamber_id=3, tool_id="ETCH-01",
                                                  chamber_code="A"),
    "track_out_before_track_in": lambda f: m.WaferStepHistory(
        wafer_id=1, route_step_id=1, lot_id=1, chamber_id=1, recipe_id=1,
        track_in=at(30), track_out=at(10),
    ),
    "split_without_child_lot": lambda f: m.LotEvent(
        lot_id=1, event_type="split", event_time=at(5)
    ),
    "spec_limits_out_of_order": lambda f: m.MetrologyPlan(
        route_step_id=2, parameter_id=2, wafers_per_lot=5, sites_per_wafer=9,
        target=300.0, lsl=310.0, usl=290.0,
    ),
    "metrology_site_off_wafer": lambda f: m.MetrologyMeasurement(
        time=at(40), wafer_id=1, route_step_id=2, parameter_id=2, site_no=1,
        site_x_mm=140.0, site_y_mm=140.0, value=300.0,
    ),
    "negative_die_count": lambda f: m.WaferBinSummary(wafer_id=1, bin_code=1, die_count=-1),
    "excursion_ends_before_start": lambda f: m.ExcursionGroundTruth(
        run_id=1, excursion_type="drift", chamber_id=1, start_time=at(100),
        end_time=at(50), description="bad window",
    ),
    "excursion_without_root_cause": lambda f: m.ExcursionGroundTruth(
        run_id=1, excursion_type="step_shift", start_time=at(100), description="no cause",
    ),
    "spatial_excursion_without_pattern": lambda f: m.ExcursionGroundTruth(
        run_id=1, excursion_type="spatial_pattern", chamber_id=1, start_time=at(100),
        description="no pattern",
    ),
    "unknown_spatial_pattern": lambda f: m.ExcursionGroundTruth(
        run_id=1, excursion_type="spatial_pattern", chamber_id=1, spatial_pattern="smiley",
        start_time=at(100), description="bad pattern",
    ),
}  # fmt: skip


@pytest.mark.parametrize("case", VIOLATIONS)
def test_database_rejects_invalid_rows(db: Session, fab: MiniFab, case: str) -> None:
    db.add(VIOLATIONS[case](fab))
    with pytest.raises(DBAPIError):
        db.flush()


def test_database_rejects_one_dimensional_wafer_map(db: Session, fab: MiniFab) -> None:
    # Raw SQL on purpose: the ORM rejects a 1-D list before it reaches Postgres, but the COPY
    # loader bypasses the ORM, so the CHECK constraint itself must hold.
    with pytest.raises(DBAPIError, match="bin_map_is_2d"):
        db.execute(
            text("INSERT INTO wafer_maps (wafer_id, tested_at, bin_map) VALUES (1, now(), :m)"),
            {"m": [1, 1, 2]},
        )
