"""Writes docs/dbt.md from dbt's manifest: a model table and a Mermaid lineage graph.

    cd dbt && dbt docs generate && cd .. && python -m waferlens.db.dbt_docs

Generated rather than a screenshot, so it can't go stale: rerun after changing models.
The 23 staging views are drawn as one node; every intermediate and mart model is its own.
"""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[3]
MANIFEST = ROOT / "dbt" / "target" / "manifest.json"
OUTPUT = ROOT / "docs" / "dbt.md"
LAYERS = ("staging", "intermediate", "marts")


def _models(manifest: dict[str, Any]) -> dict[str, dict[str, Any]]:
    return {
        uid: node
        for uid, node in manifest["nodes"].items()
        if node["resource_type"] == "model" and node["package_name"] == "waferlens"
    }


def _layer(node: dict[str, Any]) -> str:
    return next((p for p in node["fqn"] if p in LAYERS), "other")


def lineage(manifest: dict[str, Any]) -> str:
    models = _models(manifest)
    staging = {uid for uid, n in models.items() if _layer(n) == "staging"}
    name = {uid: n["name"] for uid, n in models.items()}
    edges: set[tuple[str, str]] = set()
    for uid, node in models.items():
        if uid in staging:
            continue
        for parent in node["depends_on"]["nodes"]:
            if parent in staging:
                edges.add(("staging", name[uid]))
            elif parent in models:
                edges.add((name[parent], name[uid]))

    lines = ["```mermaid", "flowchart LR"]
    lines.append(f'    staging["staging<br/>{len(staging)} views over the source tables"]')
    for layer in ("intermediate", "marts"):
        lines.append(f"    subgraph {layer}_layer [{layer}]")
        for node in sorted(models.values(), key=lambda n: n["name"]):
            if _layer(node) == layer:
                lines.append(f"        {node['name']}")
        lines.append("    end")
    lines += [f"    {a} --> {b}" for a, b in sorted(edges)]
    lines.append("```")
    return "\n".join(lines)


def model_table(manifest: dict[str, Any]) -> str:
    models = _models(manifest)
    tests: Counter[str] = Counter()
    for node in manifest["nodes"].values():
        if node["resource_type"] in ("test", "unit_test"):
            for parent in node.get("depends_on", {}).get("nodes", []):
                tests[parent] += 1
    for node in manifest.get("unit_tests", {}).values():
        for parent in node.get("depends_on", {}).get("nodes", []):
            tests[parent] += 1

    rows = ["| Model | Layer | Materialized | Tests | Description |", "|---|---|---|---|---|"]

    def order(item: tuple[str, dict[str, Any]]) -> tuple[int, str]:
        layer = _layer(item[1])
        return (LAYERS.index(layer) if layer in LAYERS else len(LAYERS), item[1]["name"])

    for uid, node in sorted(models.items(), key=order):
        if _layer(node) == "staging":
            continue
        description = " ".join(node.get("description", "").split())
        rows.append(
            f"| `{node['name']}` | {_layer(node)} | {node['config']['materialized']} | "
            f"{tests[uid]} | {description} |"
        )
    return "\n".join(rows)


def render(manifest: dict[str, Any]) -> str:
    models = _models(manifest)
    n_tests = sum(1 for n in manifest["nodes"].values() if n["resource_type"] == "test")
    n_unit = len(manifest.get("unit_tests", {}))
    counts = Counter(_layer(n) for n in models.values())
    return f"""# dbt project

Generated by `make dbt-docs` from `dbt/target/manifest.json`; don't edit by hand.

{len(models)} models ({counts["staging"]} staging views, {counts["intermediate"]} intermediate,
{counts["marts"]} marts), {n_tests} data tests and {n_unit} unit tests. Marts are a star schema
in the `marts` schema: facts at a stated grain joined to dimensions on surrogate keys, which is
what Power BI imports in phase 7.

## Lineage

{lineage(manifest)}

## Intermediate and mart models

{model_table(manifest)}
"""


def main() -> None:
    manifest = json.loads(MANIFEST.read_text())
    OUTPUT.write_text(render(manifest))
    print(f"wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
