"""Renders docs/secom_model.md from an experiment."""

from __future__ import annotations

import pandas as pd

from waferlens.ml.experiment import Experiment, Holdout
from waferlens.ml.secom import FALSE_ALARM_RATES


def _window(times: pd.Series) -> str:
    return f"{times.iloc[0]:%Y-%m-%d} → {times.iloc[-1]:%Y-%m-%d}"


def split_table(exp: Experiment) -> str:
    rows = ["| | Runs | Fails | Fail rate | Period |", "|---|---|---|---|---|"]
    for label, part in (("Train (walk-forward CV inside)", exp.train), ("Holdout", exp.test)):
        rows.append(f"| {label} | {len(part.y):,} | {int(part.y.sum())} | "
                    f"{100 * part.y.mean():.1f}% | {_window(part.time)} |")  # fmt: skip
    return "\n".join(rows)


def leakage_table(exp: Experiment) -> str:
    rows = ["| Model | Time-ordered holdout | Random split (mean ± sd) | Random / time |",
            "|---|---|---|---|"]  # fmt: skip
    for h in (exp.chosen, exp.baseline):
        r = h.random_split
        rows.append(f"| {h.config.name} | {h.scores.pr_auc:.3f} | {r.mean():.3f} ± {r.std():.3f} "
                    f"(n={len(r)}) | {r.mean() / h.scores.pr_auc:.1f}x |")  # fmt: skip
    return "\n".join(rows)


def selection_table(exp: Experiment) -> str:
    rows = ["| Model | Missing values | Feature selection | CV PR-AUC | CV ROC-AUC |",
            "|---|---|---|---|---|"]  # fmt: skip
    for config, s in sorted(exp.selection, key=lambda cs: -cs[1].pr_auc):
        mark = " **← chosen**" if config == exp.chosen.config else ""
        rows.append(f"| {config.model} | {config.missing} | {config.selection} | "
                    f"{s.pr_auc:.3f}{mark} | {s.roc_auc:.3f} |")  # fmt: skip
    prevalence = exp.selection[0][1].prevalence
    rows.append(f"| *chance* | | | *{prevalence:.3f}* | *0.500* |")
    return "\n".join(rows)


def _forward(h: Holdout, rate: float) -> str:
    recall, actual = h.forward[rate]
    return f"{100 * recall:.0f}% (at {100 * actual:.1f}%)"


def holdout_table(exp: Experiment) -> str:
    head = "| Model | PR-AUC (95% CI) | ROC-AUC |"
    sep = "|---|---|---|"
    for rate in FALSE_ALARM_RATES:
        head += f" Recall at {100 * rate:.0f}% false alarms: forward | hindsight |"
        sep += "---|---|"
    rows = [head, sep]
    for h in (exp.chosen, exp.baseline):
        row = (f"| {h.config.name} | {h.scores.pr_auc:.3f} ({h.ci[0]:.3f}–{h.ci[1]:.3f}) | "
               f"{h.scores.roc_auc:.3f} |")  # fmt: skip
        for rate in FALSE_ALARM_RATES:
            row += f" {_forward(h, rate)} | {100 * h.hindsight[rate]:.0f}% |"
        rows.append(row)
    chance = f"| *chance* | *{exp.chosen.scores.prevalence:.3f}* | *0.500* |"
    for rate in FALSE_ALARM_RATES:
        chance += f" *{100 * rate:.0f}%* | *{100 * rate:.0f}%* |"
    rows.append(chance)
    return "\n".join(rows)


def importance_table(exp: Experiment, top: int = 10) -> str:
    baseline = exp.extras.get("baseline_importance", pd.Series(dtype=float))
    baseline_rank = {s: i for i, s in enumerate(baseline.index, start=1)}
    missing = exp.train.X.isna().mean()
    fails = exp.train.y == 1
    rows = ["| Rank | Sensor | Share of importance | Rank in baseline | Missing (train) | "
            "Mean on fails vs passes (sd) |", "|---|---|---|---|---|---|"]  # fmt: skip
    total = exp.importance.sum()
    for rank, (sensor, value) in enumerate(exp.importance.head(top).items(), start=1):
        x = exp.train.X[str(sensor)]
        shift = (x[fails].mean() - x[~fails].mean()) / x.std()
        rows.append(f"| {rank} | {sensor} | {100 * value / total:.1f}% | "
                    f"{baseline_rank.get(sensor, '–')} | {100 * missing[str(sensor)]:.1f}% | "
                    f"{shift:+.2f} |")  # fmt: skip
    return "\n".join(rows)


def render(exp: Experiment) -> str:
    c, b = exp.chosen, exp.baseline
    gap = c.random_split.mean() / c.scores.pr_auc
    lift = c.scores.pr_auc / c.scores.prevalence
    recall10, actual10 = c.forward[0.10]
    cv = dict(exp.selection)[c.config].pr_auc
    verdict = (
        "The 95% interval includes chance: forward in time, the model is not reliably better "
        "than a random ranking."
        if c.ci[0] <= c.scores.prevalence
        else "The 95% interval excludes chance."
    )
    baseline_note = (
        f" The logistic baseline scored higher on the holdout ({b.scores.pr_auc:.3f}); switching "
        "to it now would be choosing the model on the test set, so the choice stands and the "
        "comparison is reported instead."
        if b.scores.pr_auc > c.scores.pr_auc
        else ""
    )
    return f"""# SECOM fail prediction

Generated by `make secom-model`; don't edit by hand. Code: `src/waferlens/ml/`; runs and the
registered model (`secom-fail-predictor` {exp.model_version}) in MLflow; scores and sensor
importance in `secom_scores` / `secom_sensor_importance` for Grafana. Data card:
[docs/data/secom.md](data/secom.md).

**On the last 30% of runs, never seen during training or model selection, the chosen model
reaches PR-AUC {c.scores.pr_auc:.3f} (95% CI {c.ci[0]:.3f}–{c.ci[1]:.3f}) against
{c.scores.prevalence:.3f} for chance ({lift:.1f}x). The same model on a random split scores
{c.random_split.mean():.3f}: a time-blind evaluation would overstate it {gap:.1f}x.**
{verdict}

## Split

{split_table(exp)}

The fail rate falls from 22% in July to 3% in September (data card), so the holdout is the
latest runs and every number below is forward in time. Model selection used only the
training period: four expanding walk-forward folds, each predicted by a model fitted on the
runs before it (the first block is never predicted).

## A random split flatters the model

{leakage_table(exp)}

Random splits put runs from the same weeks on both sides, so the model is tested on the
process state it was trained on. In production the next month is always new.

## Model selection (walk-forward CV, training period only)

{selection_table(exp)}

Every preprocessing step is fitted inside the pipeline on training rows only: dropping
constant and >50%-missing sensors, median imputation (optionally with a was-missing
indicator per sensor), scaling, and feature selection (correlation > 0.95 pruning, L1
logistic regression, or the top 40 by mutual information). LightGBM can also take the
missing values as they are ("native").

## Holdout (scored once)

{holdout_table(exp)}

The chosen configuration scored {cv:.3f} in walk-forward CV and {c.scores.pr_auc:.3f} on the
holdout: picking the best of {len(exp.selection)} configurations on {int(exp.train.y.sum())}
training fails selects partly for luck, so the winner's CV score is optimistic.{baseline_note}

*Forward*: the alarm threshold is set on the training period's walk-forward scores for that
false-alarm budget and applied unchanged to the holdout; the false-alarm rate it actually
produced is in brackets. *Hindsight*: the best recall at that budget with the threshold set
on the holdout itself, an upper bound no deployment gets.

The 10% threshold from the training period produced a {100 * actual10:.1f}% false-alarm
rate on the holdout and caught {100 * recall10:.0f}% of fails. When the process drifts, the
score distribution moves with it, and last month's threshold no longer means the same alarm
rate: a deployed model needs its threshold recalibrated on recent runs, or a rank-based
alarm (the top k% of runs each week).

## Sensors behind the scores

{importance_table(exp)}

Importance is the mean |contribution| on the holdout (TreeSHAP via LightGBM's `pred_contrib`;
|coefficient| on standardised inputs for logistic regression); a sensor's missing-value
indicator counts towards the sensor. SECOM's signals are anonymised, so this ranks sensors
but can't say what they measure. The last column is the train-period difference between
fails and passes in standard deviations.

## Limitations

- **{c.scores.fails} holdout fails**: the confidence interval is wide, and a different
  holdout boundary would move the numbers.
- **One line, three months**: nothing here says how this generalises to another line.
- **Ranking aid, not a gate**: at ROC-AUC {c.scores.roc_auc:.2f} the scores can order runs
  for inspection, but not pass or fail them. The baseline ({b.config.name}) reaches PR-AUC
  {b.scores.pr_auc:.3f}.
"""
